### ISSUE TITLE
Automatic height

### ISSUE THREAD

**Issue by tvstuff** [ujell/YUTableView-Swift#3] opened 2016-06-01 11:54 UTC
Is there any way we can use nodes to have Automatic height according to their content
same as we do in height for tableview

**Comment by ujell** [comment] 2016-06-05 16:27
Do you mean with `tableView.rowHeight = UITableViewAutomaticDimension` ? As long as you set row height to automatic and don't implement `heightForNode` it should work. Or am I missing something?

**Comment by ujell** [comment] 2016-08-15 15:33
Can't reproduce and no reply in 2 months, so I'm closing this issue.

**Closed as completed by ujell** 2016-08-15 15:33 UTC
